### PR TITLE
Implement bip352 full

### PR DESCRIPTION
**Pull request by Eunovo**
- Moved Silent Payments SPKM code to new DescriptorScriptPubKeyMan subclass
- Fixed errors
- Repositioned commits that fail to compile because they use code defined in later commits

### CODE REVIEW

**Comment by Sjors** [comment]
Couple of things I noticed on `josibake/implement-bip352-full` (which I'm assuming is mostly the same as this):

* importing a silent payment descriptor fails with "Active descriptors must be ranged". You could add a test to `wallet_silentpayments_receiving.py` for this. Not sure what the best way is to add an exception for this rule to the RPC.
* the `sp()` descriptor returned by `listdescriptors` does not have the origin prefix. This makes it look like they're randomly generated and not derived from the seed, though afaik they _are_ derived as `m/352h/0h/0h/0h/0` and `m/352h/0h/0h/1h/0`.
* can you display the `silent_payments` flags in `getwalletinfo`?
* adding an `sp()` descriptor to an existing wallet with `createwalletdescriptor silent-payment` works, but I suspect it doesn't set the silent payment flag. This could be done automatically, or the user could be asked to do it manually with `setwalletflag`.

**Comment by Sjors** [comment]
Also, using the GUI to send to a silent payment address results in some sort of malformed non-standard output. So you may want to disable or fix that :-) Tried with both `josibake/implement-bip352-full` and `josibake/implement-bip352-sending`.

**Comment by Sjors** [comment]
It would be useful if `listreceivedbyaddress` or `listreceivedbylabel` is able to figure out which silent payments arrived to which label.

**Comment by Sjors** [comment]
> * importing a silent payment descriptor fails with "Active descriptors must be ranged"

Come to think of it, it's nice if you can specify how many labels have been used so far. Otherwise you have to generate enough labels and then do another rescan. We could shoehorn this number into range `argument`. In that case it's fine to keep this argument mandatory, as long as the docs explain it.

**Comment by Sjors** [comment]
I managed to hit `Assertion failed: (sp_spk_man != nullptr), function operator(), file walletdb.cpp, line 962.` The wallet started blank, I then imported a silent payment descriptor (with private keys). I created two labels, received a transaction to the second label and sent that coin out.

Recreating the wallet, generating new addresses for each label, and then rescanning the existing transactions works. Once I restart QT and load the wallet again it crashes.

If I skip the rescan the transactions don't show up (as expected). But that does avoid the crash after a restart. But then rescanwallet doesn't reveal the earlier transactions.

This behavior seems quite consistent.

**Comment by Sjors** [comment]
One more thing: I tried to make a watch-only version of the wallet. I first obtained the descriptor with only the scan key using `listdescriptors`. But then `importdescriptors` fails with `Cannot import private keys to a wallet with private keys disabled`.

Disabling that check triggers `Assertion failed: (keydata), function GetPubKey, file key.cpp, line 190.`, so I guess this would be a bit more involved :-)

**Comment by Eunovo** [comment]
@Sjors added and tested importdescriptors support with watch-only wallet in https://github.com/josibake/bitcoin/pull/3

**Comment by Eunovo** [comment]
> Come to think of it, it's nice if you can specify how many labels have been used so far. Otherwise you have to generate enough labels and then do another rescan. We could shoehorn this number into range `argument`. In that case it's fine to keep this argument mandatory, as long as the docs explain it.
> 
> For the same reason it would be useful if `listdescriptors` pretends it's ranged and shows the number of generated labels.

@Sjors SGTM but https://github.com/bitcoin/bips/blob/master/bip-0352.mediawiki#scanning specifies that implementations scan for labels until no new payments are found. Adding a label range to `importdescriptors` might imply that we will not scan pass that range which is contrary to what's specified in the bip

**Comment by Eunovo** [comment]
> * can you display the `silent_payments` flags in `getwalletinfo`?
> * adding an `sp()` descriptor to an existing wallet with `createwalletdescriptor silent-payment` works, but I suspect it doesn't set the silent payment flag. This could be done automatically, or the user could be asked to do it manually with `setwalletflag`.

@Sjors Will look into these

**Comment by Eunovo** [comment]
> * importing a silent payment descriptor fails with "Active descriptors must be ranged". You could add a test to `wallet_silentpayments_receiving.py` for this. Not sure what the best way is to add an exception for this rule to the RPC.

Taken care of in https://github.com/josibake/bitcoin/pull/3

> the sp() descriptor returned by listdescriptors does not have the origin prefix. This makes it look like they're randomly generated and not derived from the seed, though afaik they are derived as m/352h/0h/0h/0h/0 and m/352h/0h/0h/1h/0.

@Sjors They are derived but current `sp()` design does not preserve extended key information. Apart from the first derivation, we don't need to derive anything else. @josibake any thoughts?

**Comment by Sjors** [comment]
> specifies that implementations scan for labels until no new payments are found.

It's possible that I used labels in the "wrong" order - and so the one unused label caused the import to not find my transaction?

But this strategy seems problematic, because you can't guarantee that people will pay to your label. Oh hi gap problem! :-) cc @josibake.

> Adding a label range to importdescriptors might imply that we will not scan pass that range which is contrary to what's specified in the bip

Generally when you specify a range for a regular descriptor, it will top up the key pool every time it finds a used address. So it will go past the specified range.

> does not preserve extended key information

I think it should.

I'll try out #3.

**Comment by Eunovo** [comment]
We need to wait to hear from @josibake Which will probably be next week. However, this PR does not need to remain open as the changes from this PR are already on the josibake/implement-bip352-full branch, so, I am closing this.

**Comment by josibake** [comment]
@Eunovo @Sjors I created https://github.com/josibake/bitcoin/discussions/4 to better track meta discussion related to silent payments implementation

**Pull request closed without merging**
